name: Evaluate Memory Card Game

on:
  push:
    branches:
      - main  # Or another branch participants will push to

jobs:
  evaluate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version

      - name: Install dependencies
        run: npm install  # Run this if your project requires dependencies (e.g., if using npm)

      - name: Run tests or evaluation script
        run: node evaluate.js  # This will run the custom evaluation script you create
